workflows:
  android-kivy:
    name: Weather APK
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "org.weather.app"
    scripts:
      - name: Install system deps
        script: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 \
            python3-pip \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libncurses5

      - name: Install Buildozer
        script: |
          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: Build APK
        script: |
          buildozer android debug
    artifacts:
      - bin/*.apk
